"""
Basic tests for the Task 2 Transformer model system.

These are intentionally beginner-friendly smoke tests:
  - dataset loads
  - model forward pass works
  - outputs generated by training/evaluation exist
  - decoding/prediction artifacts are non-empty
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import torch

TASK2_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = TASK2_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from dataset import build_dataloaders, build_datasets  # noqa: E402
from model import PhysicsSeq2SeqTransformer  # noqa: E402
from utils import invert_vocab, load_vocab  # noqa: E402


TASK1_2_ROOT = TASK2_ROOT.parent

VOCAB_PATH = TASK1_2_ROOT / "outputs" / "vocab.json"
MODEL_PATH = TASK2_ROOT / "outputs" / "model.pt"
PREDICTIONS_PATH = TASK2_ROOT / "outputs" / "predictions.json"
PREDICTIONS_READABLE_PATH = TASK2_ROOT / "outputs" / "predictions_readable.json"
LOSS_HISTORY_PATH = TASK2_ROOT / "outputs" / "loss_history.json"
LOSS_PLOT_PATH = TASK2_ROOT / "outputs" / "loss_plot.png"


def main() -> None:
    if not VOCAB_PATH.is_file():
        print(f"FAIL: Missing vocab: {VOCAB_PATH}", file=sys.stderr)
        sys.exit(1)

    vocab = load_vocab(VOCAB_PATH)
    pad_id = len(vocab)
    vocab_size = pad_id + 1

    train_ds, val_ds, test_ds = build_datasets()
    if len(train_ds) <= 0:
        print("FAIL: train dataset is empty.", file=sys.stderr)
        sys.exit(1)

    train_loader, _val_loader, _test_loader = build_dataloaders(
        train_ds=train_ds,
        val_ds=val_ds,
        test_ds=test_ds,
        pad_id=pad_id,
        batch_size=2,
        max_src_len=128,
        max_tgt_len=128,
    )

    # Model forward pass smoke test.
    device = torch.device("cpu")
    model = PhysicsSeq2SeqTransformer(
        vocab_path=VOCAB_PATH,
        pad_id=pad_id,
        vocab_size=vocab_size,
        d_model=64,
        nhead=4,
        num_encoder_layers=1,
        num_decoder_layers=1,
        dim_feedforward=128,
        dropout=0.1,
    ).to(device)

    batch = next(iter(train_loader))
    src_ids = batch["input_ids"].to(device)
    tgt_ids = batch["target_ids"].to(device)
    decoder_in = tgt_ids[:, :-1]
    logits = model(src_ids, decoder_in)
    if logits.dim() != 3:
        print("FAIL: model output logits have unexpected shape.", file=sys.stderr)
        sys.exit(1)

    # Check training/evaluation outputs.
    if not MODEL_PATH.is_file():
        print(f"FAIL: Missing model checkpoint: {MODEL_PATH}", file=sys.stderr)
        sys.exit(1)
    if not PREDICTIONS_PATH.is_file():
        print(f"FAIL: Missing predictions artifact: {PREDICTIONS_PATH}", file=sys.stderr)
        sys.exit(1)
    if not PREDICTIONS_READABLE_PATH.is_file():
        print(f"FAIL: Missing readable predictions artifact: {PREDICTIONS_READABLE_PATH}", file=sys.stderr)
        sys.exit(1)
    if not LOSS_HISTORY_PATH.is_file():
        print(f"FAIL: Missing loss history artifact: {LOSS_HISTORY_PATH}", file=sys.stderr)
        sys.exit(1)
    if not LOSS_PLOT_PATH.is_file():
        print(f"FAIL: Missing loss plot artifact: {LOSS_PLOT_PATH}", file=sys.stderr)
        sys.exit(1)

    with open(PREDICTIONS_PATH, encoding="utf-8") as f:
        pred_data = json.load(f)

    predictions = pred_data.get("predictions") or []
    if not predictions:
        print("FAIL: predictions.json contains no predictions.", file=sys.stderr)
        sys.exit(1)

    # Ensure accuracy is present and in a sane range.
    acc = pred_data.get("token_accuracy")
    if not isinstance(acc, (int, float)):
        print("FAIL: token_accuracy missing or invalid.", file=sys.stderr)
        sys.exit(1)
    if acc < 0.0 or acc > 1.0:
        print("FAIL: token_accuracy out of expected range.", file=sys.stderr)
        sys.exit(1)
    bleu = pred_data.get("bleu_score")
    if not isinstance(bleu, (int, float)) or not (0.0 <= bleu <= 1.0):
        print("FAIL: bleu_score missing or out of range.", file=sys.stderr)
        sys.exit(1)
    exact = pred_data.get("exact_match_accuracy")
    if not isinstance(exact, (int, float)) or not (0.0 <= exact <= 1.0):
        print("FAIL: exact_match_accuracy missing or out of range.", file=sys.stderr)
        sys.exit(1)

    # (Optional) validate decode mapping exists.
    _id_to_token = invert_vocab(vocab)

    print("Task 2 model tests passed")


if __name__ == "__main__":
    main()

